logo: "assets/img/logo.png"
favicon: "assets/favicon.png"

# Info
address: "Warsaw, Poland"
email: "mgu@mikh.pro"
# phone: "123456"

# Socials

twitter: "#"
facebook: "#"
github: "https://github.com/mguzelevich"
